/**
 * The I Style catalogue. Prices are intentionally NOT shown — every product is
 * "price on request" and enquiries go to WhatsApp with the product pre-filled.
 * Descriptions only describe what is visible in the photography.
 */

export type Category = "footwear" | "bags" | "accessories";

export type Product = {
  slug: string;
  name: string; // the piece's name
  line: string; // what it is
  category: Category;
  type: string; // filter facet (Slide, Thong, Briefcase…)
  colour: string;
  materials: string[];
  features: string[];
  blurb: string; // one line for cards
  story: string; // 2–3 sentences for the product page
  images: string[]; // first = hero
  swatch: string; // dominant colour hex for UI accents
  signature?: boolean;
};

const foot = (p: Omit<Product, "category">): Product => ({ ...p, category: "footwear" });
const bag = (p: Omit<Product, "category">): Product => ({ ...p, category: "bags" });
const acc = (p: Omit<Product, "category">): Product => ({ ...p, category: "accessories" });

export const products: Product[] = [
  // ───────────────────────────── FOOTWEAR ─────────────────────────────
  foot({
    slug: "the-palar-cross",
    name: "The Palar",
    line: "Cross-strap slide",
    type: "Slide",
    colour: "Tan croc / Black",
    materials: ["Croc-embossed leather", "Smooth leather", "Moulded sole"],
    features: ["Two crossed straps", "Contrast tan + black straps", "Padded footbed", "Low-profile sole"],
    blurb: "Two straps, crossed and stitched — tan croc over black.",
    story:
      "Our signature. One strap in tan croc-embossed leather, one in smooth black, crossed over the foot and anchored into a padded footbed. It holds the foot without a buckle and looks just as right with a mundu as with denim.",
    images: ["/img/foot/cross-strap-teal.webp", "/img/foot/cross-strap-sand.webp", "/img/foot/cross-strap-light-tall.webp"],
    swatch: "#a8794e",
    signature: true,
  }),
  foot({
    slug: "the-weave",
    name: "The Weave",
    line: "Woven toe-ring slide",
    type: "Toe-ring",
    colour: "Black",
    materials: ["Woven leather strips", "Leather-lined footbed"],
    features: ["Hand-interlaced straps", "Toe ring", "Cushioned footbed", "Stitched welt"],
    blurb: "Leather strips interlaced by hand over a toe-ring base.",
    story:
      "Eight leather strips, woven over and under across the forefoot so the upper flexes with every step. A toe ring keeps it secure; the cushioned footbed does the rest.",
    images: ["/img/foot/woven-toe-ring-sage.webp"],
    swatch: "#1d1b1a",
    signature: true,
  }),
  foot({
    slug: "the-contrast-v",
    name: "The Contrast",
    line: "V-strap thong",
    type: "Thong",
    colour: "Black / Tan",
    materials: ["Pebble-grain leather", "Smooth tan leather overlay"],
    features: ["Tan V-strap overlay", "Metal accent", "Quilted padded footbed", "Toe post"],
    blurb: "Black thong with a tan leather V laid over the strap.",
    story:
      "A classic toe-post thong with a tan leather overlay stitched down the V of the strap. The footbed is padded and channel-quilted, so it feels broken-in from the first wear.",
    images: ["/img/foot/tan-v-thong-sage.webp"],
    swatch: "#b97a45",
  }),
  foot({
    slug: "the-twin-buckle",
    name: "The Twin Buckle",
    line: "Double-buckle slide",
    type: "Slide",
    colour: "Black",
    materials: ["Smooth leather", "Metal buckles", "Moulded footbed"],
    features: ["Two adjustable buckles", "Perforated vamp", "Contoured footbed", "Toe loop"],
    blurb: "Smooth black leather, two buckles and a perforated vamp.",
    story:
      "A broad, structured upper with two buckle straps that let you set the fit exactly. Perforations across the vamp let air through on long days; the contoured footbed cups the heel.",
    images: ["/img/foot/double-buckle-sage.webp", "/img/foot/double-buckle-white.webp", "/img/foot/double-buckle-top.webp"],
    swatch: "#232628",
    signature: true,
  }),
  foot({
    slug: "the-arcot",
    name: "The Arcot",
    line: "H-strap toe-post sandal",
    type: "Toe-post",
    colour: "Cognac / Tan suede",
    materials: ["Smooth cognac leather", "Tan suede", "Ridged rubber outsole"],
    features: ["H-strap with suede panel", "Stitched toe post with stud", "Ridged grip outsole", "Brown footbed"],
    blurb: "Cognac leather over tan suede, on a ridged outsole.",
    story:
      "Named after the old town down the road. Two cognac straps crossed with a tan suede panel, saddle-stitched and finished with a stud at the toe post. The deep-ridged outsole grips on wet stone.",
    images: [
      "/img/foot/h-strap-sage.webp",
      "/img/foot/h-strap-white.webp",
      "/img/foot/h-strap-light.webp",
      "/img/foot/h-strap-hero.webp",
    ],
    swatch: "#8a4f2a",
    signature: true,
  }),
  foot({
    slug: "the-croc-buckle",
    name: "The Croc Buckle",
    line: "Croc-embossed buckle slide",
    type: "Slide",
    colour: "Dark brown croc",
    materials: ["Croc-embossed leather", "Metal buckle", "Moulded sole"],
    features: ["Two wide bands", "Single buckle", "Toe channel footbed", "Contrast black sole"],
    blurb: "Deep brown croc emboss, two bands and a single buckle.",
    story:
      "Two broad bands of croc-embossed leather in a deep, glossy brown, joined by a polished buckle. Dressy enough for a function, comfortable enough for the walk there.",
    images: ["/img/foot/croc-buckle-sage.webp", "/img/foot/croc-buckle-white.webp"],
    swatch: "#4a2617",
  }),
  foot({
    slug: "the-navy-cross",
    name: "The Navy Cross",
    line: "Patent cross-strap slide",
    type: "Slide",
    colour: "Navy / Grey",
    materials: ["Patent-finish leather", "Moulded footbed"],
    features: ["Crossed straps in two colours", "High-gloss finish", "Dark footbed"],
    blurb: "Navy and dove-grey straps in a high-gloss finish.",
    story:
      "The cross-strap silhouette in a glossy finish — one strap navy, one dove grey. A sharp, modern take for anyone who'd rather not wear brown.",
    images: ["/img/foot/navy-cross-sage.webp"],
    swatch: "#1f2c4a",
  }),
  foot({
    slug: "the-charcoal-cross",
    name: "The Charcoal Cross",
    line: "Croc cross-strap slide",
    type: "Slide",
    colour: "Charcoal croc",
    materials: ["Croc-embossed leather", "Metal buckles", "Padded grey footbed"],
    features: ["Wide crossed straps", "Twin side buckles", "Soft padded footbed", "Stitched sole edge"],
    blurb: "Wide croc-embossed straps with twin buckles at the side.",
    story:
      "Broad charcoal straps pressed with a fine croc grain, crossed over a plush grey footbed and fastened with two buckles. Substantial, soft and very easy to live in.",
    images: ["/img/foot/croc-cross-buckle-sage.webp"],
    swatch: "#3a3a3a",
  }),
  foot({
    slug: "the-breeze",
    name: "The Breeze",
    line: "Perforated toe-loop slide",
    type: "Toe-ring",
    colour: "Black",
    materials: ["Perforated woven-effect leather", "Smooth leather"],
    features: ["Perforated vamp", "Toe loop", "Padded footbed", "Clean moulded sole"],
    blurb: "A perforated black vamp that breathes on the hottest days.",
    story:
      "A single sweeping vamp in perforated, woven-effect leather with a smooth toe loop. Made for Tamil Nadu summers — the air moves through it.",
    images: ["/img/foot/perforated-slide-sage.webp", "/img/foot/perforated-slide-sage-2.webp"],
    swatch: "#1c1c1c",
  }),
  foot({
    slug: "the-buckled-post",
    name: "The Buckled Post",
    line: "Multi-strap toe-post sandal",
    type: "Toe-post",
    colour: "Black",
    materials: ["Textured leather", "Smooth leather", "Metal buckle"],
    features: ["Three-strap upper", "Buckle adjust", "Toe post with stud", "Moulded sole"],
    blurb: "Three straps, a buckle and a toe post — built to stay put.",
    story:
      "Three textured straps fan out from a studded toe post, with a buckle to fine-tune the fit. A secure, everyday sandal that keeps its shape.",
    images: ["/img/foot/multi-strap-thong-plinth.webp"],
    swatch: "#202020",
  }),
  foot({
    slug: "the-cognac-cross",
    name: "The Cognac Cross",
    line: "Cross-strap thong",
    type: "Thong",
    colour: "Cognac / Black",
    materials: ["Croc-embossed leather", "Smooth leather"],
    features: ["Crossed cognac strap", "Buckle detail", "Toe post", "Black footbed"],
    blurb: "Cognac croc crossing a black base, with a buckle detail.",
    story:
      "A thong with a cognac croc strap that crosses the foot and closes with a small buckle. Warm leather on a black footbed — the pairing never dates.",
    images: ["/img/foot/cognac-cross-thong-plinth.webp"],
    swatch: "#7a3f1f",
  }),
  foot({
    slug: "the-croc-thong",
    name: "The Croc Thong",
    line: "Croc-embossed thong",
    type: "Thong",
    colour: "Black croc",
    materials: ["Croc-embossed leather", "Smooth footbed"],
    features: ["Wide croc strap", "Toe post", "Stitched footbed edge"],
    blurb: "A wide strap of black croc emboss on a smooth footbed.",
    story:
      "One broad strap pressed with a croc pattern that catches the light as you walk. Simple, polished, and stitched all round the footbed.",
    images: ["/img/foot/croc-thong-plinth.webp"],
    swatch: "#151515",
  }),
  foot({
    slug: "the-sunday",
    name: "The Sunday",
    line: "Tan leather thong",
    type: "Thong",
    colour: "Tan",
    materials: ["Smooth tan leather", "Stitched leather footbed"],
    features: ["Tan strap", "Toe post", "Stitched footbed", "Light, flexible sole"],
    blurb: "All-tan, all-leather, made for slow mornings.",
    story:
      "Tan from strap to footbed, with a contrast stitch running around the edge. The leather darkens beautifully as you wear it in.",
    images: ["/img/foot/tan-thong-plinth.webp"],
    swatch: "#b5743f",
  }),
  foot({
    slug: "the-monochrome",
    name: "The Monochrome",
    line: "Two-tone thong",
    type: "Thong",
    colour: "Black / White",
    materials: ["Smooth leather", "Contrast leather trim"],
    features: ["Black strap with white trim", "Toe post", "Cushioned footbed"],
    blurb: "Black with a crisp white trim — easy with everything.",
    story:
      "A clean black thong lifted with a white leather trim along the strap. Goes with linen, goes with denim, goes with whatever's clean.",
    images: ["/img/foot/mono-thong-plinth.webp"],
    swatch: "#2a2a2a",
  }),

  // ───────────────────────────── BAGS ─────────────────────────────
  bag({
    slug: "the-professional",
    name: "The Professional",
    line: "Laptop briefcase",
    type: "Briefcase",
    colour: "Black / Tan",
    materials: ["Textured black leather", "Smooth tan leather trim", "Metal hardware"],
    features: ["Twin top handles", "Tan straps wrap the body", "Zip-around top", "Detachable shoulder strap"],
    blurb: "Textured black body, tan leather wrapping it like a frame.",
    story:
      "Our signature bag — 'bags that go the distance', as we put it on Instagram. A structured black body, tan leather straps running up and over into the handles, and room for a laptop and a working day.",
    images: ["/img/bags/professional-studio.webp", "/img/bags/professional-white.webp", "/img/bags/professional-light.webp"],
    swatch: "#a8693a",
    signature: true,
  }),
  bag({
    slug: "the-minimalist",
    name: "The Minimalist",
    line: "Document & laptop case",
    type: "Document case",
    colour: "Navy",
    materials: ["Smooth navy leather"],
    features: ["Cut-out handles", "Strap-and-loop closure", "Slim profile", "Unlined edges, painted"],
    blurb: "One piece of navy leather, cut-out handles, nothing extra.",
    story:
      "A slim folio-style case with handles cut straight into the leather and a single strap closure. Holds a laptop, a notebook and a few documents — and nothing else.",
    images: ["/img/bags/minimalist-studio.webp", "/img/bags/minimalist-white.webp"],
    swatch: "#233a66",
    signature: true,
  }),
  bag({
    slug: "the-explorer",
    name: "The Explorer",
    line: "Canvas & leather duffel",
    type: "Duffel",
    colour: "Forest green / Tan",
    materials: ["Heavy canvas", "Tan leather base & trim", "Metal hardware"],
    features: ["Leather base & corners", "Front zip pocket with leather piping", "Rolled leather handles", "Shoulder strap"],
    blurb: "Forest-green canvas on a tan leather base.",
    story:
      "Heavy green canvas, a tan leather base that takes the knocks, and a long front pocket trimmed in leather. Packs for a long weekend and looks better every trip.",
    images: ["/img/bags/explorer-studio.webp", "/img/bags/explorer-white.webp"],
    swatch: "#1f4a3f",
    signature: true,
  }),
  bag({
    slug: "the-explorer-burgundy",
    name: "The Explorer — Burgundy",
    line: "Canvas & leather duffel",
    type: "Duffel",
    colour: "Burgundy / Navy",
    materials: ["Burgundy canvas", "Navy leather base & handles"],
    features: ["Leather base & corners", "Front zip pocket", "Navy rolled handles", "Shoulder strap"],
    blurb: "The Explorer in burgundy canvas with navy leather.",
    story:
      "Same build as The Explorer, recoloured: deep burgundy canvas with a navy leather base, corners and handles.",
    images: ["/img/bags/burgundy-explorer-white.webp"],
    swatch: "#5a2430",
  }),
  bag({
    slug: "the-classic-backpack",
    name: "The Classic",
    line: "Woven leather backpack",
    type: "Backpack",
    colour: "Brown",
    materials: ["Woven-texture leather", "Smooth brown leather", "Metal zips"],
    features: ["Woven-texture panels", "Smooth centre stripe", "Leather-reinforced base corners", "Padded straps"],
    blurb: "Woven-texture leather split by a smooth centre stripe.",
    story:
      "A clean dome-shaped backpack in woven-texture leather, with a smooth brown stripe running down the middle and reinforced corners at the base.",
    images: ["/img/bags/classic-backpack-studio.webp", "/img/bags/classic-backpack-white.webp"],
    swatch: "#5b3a24",
  }),
  bag({
    slug: "the-traveler",
    name: "The Traveler",
    line: "Weekend duffel",
    type: "Duffel",
    colour: "Espresso",
    materials: ["Smooth espresso leather", "Metal hardware"],
    features: ["Rolled leather handles", "Wide zip opening", "Detachable strap", "Panelled body"],
    blurb: "A deep espresso duffel for two nights away.",
    story:
      "Smooth espresso leather, panelled and stitched into a roomy barrel shape. The wide opening makes packing easy; the leather makes arriving easier.",
    images: ["/img/bags/traveler-studio.webp", "/img/bags/traveler-white.webp"],
    swatch: "#3b2016",
  }),
  bag({
    slug: "the-essential",
    name: "The Essential",
    line: "Travel duffel",
    type: "Duffel",
    colour: "Tan",
    materials: ["Smooth tan leather", "Metal hardware"],
    features: ["Rolled leather handles", "Zip top", "Detachable strap", "Embossed name plate"],
    blurb: "The Traveler's lighter-hearted twin, in tan.",
    story:
      "The same generous duffel cut in a light tan leather that will deepen to honey over the years.",
    images: ["/img/bags/essential-studio.webp", "/img/bags/essential-white.webp"],
    swatch: "#b98b5e",
  }),
  bag({
    slug: "the-voyager",
    name: "The Voyager",
    line: "Embossed duffel",
    type: "Duffel",
    colour: "Cognac",
    materials: ["Cognac leather", "Embossed centre panel"],
    features: ["Embossed texture panel", "Rolled handles", "Zip top", "Shoulder strap"],
    blurb: "Cognac duffel with a pressed-texture centre panel.",
    story:
      "A cognac duffel with a textured panel pressed into the centre — a little detail you notice up close.",
    images: ["/img/bags/cognac-duffel-white.webp", "/img/bags/cognac-duffel-white-2.webp"],
    swatch: "#a0603a",
  }),
  bag({
    slug: "the-nocturne",
    name: "The Nocturne",
    line: "Croc-embossed duffel",
    type: "Duffel",
    colour: "Dark brown croc",
    materials: ["Croc-embossed leather", "Metal hardware"],
    features: ["All-over croc emboss", "Rolled handles", "Zip top", "Shoulder strap"],
    blurb: "A dark-brown croc duffel for evenings and occasions.",
    story:
      "The duffel shape in an all-over croc emboss, deep brown with a soft gloss. Equally at home on a train rack or a wedding weekend.",
    images: ["/img/bags/croc-duffel-white.webp"],
    swatch: "#3a1d12",
  }),
  bag({
    slug: "the-onyx",
    name: "The Onyx",
    line: "Croc-panel duffel",
    type: "Duffel",
    colour: "Black",
    materials: ["Smooth black leather", "Croc-embossed panel"],
    features: ["Croc-embossed centre panel", "Rolled handles", "Side strap rings", "Zip top"],
    blurb: "Black on black: smooth ends, croc-embossed middle.",
    story:
      "A black barrel duffel with smooth leather ends and a croc-embossed body. The kind of bag that looks expensive without trying.",
    images: ["/img/bags/onyx-croc-duffel.webp", "/img/workshop/croc-duffel-mat.webp"],
    swatch: "#141414",
  }),
  bag({
    slug: "the-racer",
    name: "The Racer",
    line: "Striped barrel duffel",
    type: "Duffel",
    colour: "Black / Red",
    materials: ["Black leather", "Red leather stripes & piping"],
    features: ["Twin red racing stripes", "Red piping on the ends", "Red handles", "Shoulder strap"],
    blurb: "Black barrel duffel with twin red stripes and piping.",
    story:
      "A gym-to-weekend barrel bag: black leather, two red stripes running all the way round, and red piping on the ends.",
    images: ["/img/bags/racer-duffel.webp", "/img/bags/racer-duffel-2.webp", "/img/workshop/racer-held.webp"],
    swatch: "#a3161c",
  }),
  bag({
    slug: "the-diagonal",
    name: "The Diagonal",
    line: "Split-panel briefcase",
    type: "Briefcase",
    colour: "Black",
    materials: ["Smooth black leather", "Croc-embossed leather"],
    features: ["Diagonal smooth/croc split", "Twin handles", "Zip top", "Shoulder strap"],
    blurb: "Smooth leather and croc emboss, split on the diagonal.",
    story:
      "A slim briefcase cut on a diagonal — smooth black above, croc emboss below. One of those designs that came off the cutting mat and stayed.",
    images: ["/img/bags/diagonal-croc-brief.webp", "/img/workshop/croc-on-mat.webp", "/img/workshop/cutting-mat-brief.webp"],
    swatch: "#191919",
  }),
  bag({
    slug: "the-weaver",
    name: "The Weaver",
    line: "Woven weekender",
    type: "Duffel",
    colour: "Tan woven / Espresso",
    materials: ["Woven-texture tan leather", "Espresso leather"],
    features: ["Woven-texture front", "Espresso base & handles", "Front zip pocket", "Name plate"],
    blurb: "Tan woven-texture front on an espresso leather body.",
    story:
      "A boxy weekender with a tan woven-texture front, espresso leather base and a long zip pocket. Photographed here straight off the workbench.",
    images: ["/img/bags/woven-weekender.webp", "/img/workshop/bench-woven.webp", "/img/workshop/woven-closeup.webp"],
    swatch: "#b8693a",
  }),
  bag({
    slug: "the-ledger",
    name: "The Ledger",
    line: "Croc-panel briefcase",
    type: "Briefcase",
    colour: "Black",
    materials: ["Smooth black leather", "Croc-embossed panels"],
    features: ["Croc-embossed front panels", "Twin handles", "Zip top", "Shoulder strap"],
    blurb: "Croc-embossed panels framed in smooth black.",
    story:
      "A working briefcase with croc-embossed front panels set into a smooth black frame. Quiet from across the room, rich up close.",
    images: ["/img/bags/croc-panel-brief.webp"],
    swatch: "#121212",
  }),
  bag({
    slug: "the-slate",
    name: "The Slate",
    line: "Striped croc briefcase",
    type: "Briefcase",
    colour: "Slate grey",
    materials: ["Croc-embossed grey leather", "Woven cotton webbing"],
    features: ["Twin webbing stripes", "Croc emboss", "Twin handles", "Shoulder strap"],
    blurb: "Slate-grey croc with twin cream webbing stripes.",
    story:
      "A slate-grey croc briefcase with two cream webbing stripes running into the handles — here's one fresh off the floor.",
    images: ["/img/bags/slate-stripe-brief.webp", "/img/workshop/slate-held.webp", "/img/workshop/slate-brief-table.webp"],
    swatch: "#5d5a57",
  }),
  bag({
    slug: "the-night-train",
    name: "The Night Train",
    line: "Croc weekender",
    type: "Duffel",
    colour: "Black croc",
    materials: ["Croc-embossed black leather", "Metal hardware"],
    features: ["Front zip pocket", "Rolled handles", "Structured base", "Shoulder strap"],
    blurb: "A structured black croc weekender with a front zip.",
    story:
      "Structured, black and croc-embossed, with a front zip pocket for tickets and chargers. Built for overnight trains and early arrivals.",
    images: ["/img/bags/onyx-weekender.webp", "/img/workshop/floor-duffel.webp"],
    swatch: "#161616",
  }),
  bag({
    slug: "the-courier",
    name: "The Courier",
    line: "Croc-pocket briefcase",
    type: "Briefcase",
    colour: "Black",
    materials: ["Smooth black leather", "Croc-embossed pocket"],
    features: ["Croc-embossed front pocket", "Twin handles", "Zip top", "Shoulder strap"],
    blurb: "Smooth black briefcase with a croc-embossed front pocket.",
    story: "A compact briefcase with one statement — a croc-embossed front pocket. Everything else stays out of the way.",
    images: ["/img/bags/croc-pocket-brief.webp"],
    swatch: "#171717",
  }),
  bag({
    slug: "the-tanner",
    name: "The Tanner",
    line: "Woven-panel briefcase",
    type: "Briefcase",
    colour: "Black / Tan woven",
    materials: ["Black leather", "Tan woven-texture leather"],
    features: ["Tan woven-texture panels", "Black frame & handles", "Zip top", "Shoulder strap"],
    blurb: "Tan woven-texture panels set into black leather.",
    story: "Two tan woven-texture panels framed in black leather — a warm, textured face for a serious bag.",
    images: ["/img/bags/woven-panel-brief.webp", "/img/workshop/woven-brief-held.webp"],
    swatch: "#a5622f",
  }),
  bag({
    slug: "the-heritage",
    name: "The Heritage",
    line: "Flap briefcase",
    type: "Briefcase",
    colour: "Vintage tan",
    materials: ["Burnished tan leather", "Metal hardware"],
    features: ["Full front flap", "Strap-and-loop closure", "Twin handles", "Burnished finish"],
    blurb: "Burnished tan leather with a full front flap.",
    story:
      "A traditional flap briefcase in burnished tan leather that shows every crease and keeps them all — it only gets better.",
    images: ["/img/bags/heritage-flap-brief.webp"],
    swatch: "#9c5a2c",
  }),
  bag({
    slug: "the-sand-explorer",
    name: "The Explorer — Sand",
    line: "Canvas & leather duffel",
    type: "Duffel",
    colour: "Sand / Cognac",
    materials: ["Sand canvas", "Cognac leather trim & corners"],
    features: ["Leather corners & straps", "Leather patch", "Rolled handles", "Shoulder strap"],
    blurb: "Sand canvas, cognac leather corners and straps.",
    story: "A lighter Explorer in sand-coloured canvas with cognac leather corners, straps and handles.",
    images: ["/img/bags/sand-canvas-duffel.webp"],
    swatch: "#c8a77a",
  }),
  bag({
    slug: "the-ranger",
    name: "The Ranger",
    line: "Forest canvas duffel",
    type: "Duffel",
    colour: "Forest green / Cognac",
    materials: ["Forest-green canvas", "Cognac leather"],
    features: ["Leather corners & straps", "Leather patch", "Rolled handles", "Shoulder strap"],
    blurb: "Forest canvas with cognac leather straps and patch.",
    story: "Forest-green canvas and cognac leather — the Explorer's cousin with straps running the full height of the bag.",
    images: ["/img/bags/forest-canvas-duffel.webp"],
    swatch: "#1d4a40",
  }),
  bag({
    slug: "the-city",
    name: "The City",
    line: "Zip briefcase",
    type: "Briefcase",
    colour: "Black",
    materials: ["Textured black leather", "Metal zips"],
    features: ["Vertical front zip pocket", "Twin handles", "Zip top", "Shoulder strap"],
    blurb: "A clean black briefcase with a vertical zip pocket.",
    story: "Plain, black and practical, with a vertical zip pocket for the things you reach for most.",
    images: ["/img/bags/city-brief.webp", "/img/workshop/black-brief-held.webp"],
    swatch: "#1b1b1b",
  }),
  bag({
    slug: "the-cognac",
    name: "The Cognac",
    line: "Everyday briefcase",
    type: "Briefcase",
    colour: "Cognac",
    materials: ["Burnished cognac leather", "Metal hardware"],
    features: ["Front slip pocket", "Twin handles", "Zip top", "Shoulder strap"],
    blurb: "Burnished cognac with a front slip pocket.",
    story: "An everyday briefcase in burnished cognac leather with a front slip pocket. Shown here in the workshop, just finished.",
    images: ["/img/bags/cognac-brief.webp", "/img/workshop/cognac-brief-held.webp"],
    swatch: "#9a5428",
  }),

  // ───────────────────────────── ACCESSORIES ─────────────────────────────
  acc({
    slug: "watch-roll-tan",
    name: "Watch Roll",
    line: "Single-watch travel roll",
    type: "Travel",
    colour: "Tan / Grey",
    materials: ["Smooth tan leather", "Felt lining", "Leather tie"],
    features: ["Padded watch bolster", "Felt-lined interior", "Wrap-around tie"],
    blurb: "A tan roll that keeps one watch safe on the road.",
    story: "Lay the watch on the bolster, roll it up, wrap the tie. Tan leather outside, soft felt inside.",
    images: ["/img/acc/watch-roll-white.webp", "/img/acc/watch-roll-wood.webp"],
    swatch: "#b47a45",
  }),
  acc({
    slug: "watch-roll-pebble",
    name: "Watch Roll — Pebble",
    line: "Single-watch travel roll",
    type: "Travel",
    colour: "Black pebble",
    materials: ["Pebble-grain black leather", "Leather tie"],
    features: ["Pebble grain", "Wrap-around tie", "Padded bolster"],
    blurb: "The watch roll in black pebble-grain leather.",
    story: "The same roll in a black pebble grain that hides scuffs and feels great in the hand.",
    images: ["/img/acc/watch-roll-black.webp", "/img/acc/watch-roll-black-closed.webp"],
    swatch: "#1a1a1a",
  }),
  acc({
    slug: "spectacle-sleeve",
    name: "Spectacle Sleeve",
    line: "Slip-in glasses sleeve",
    type: "Cases",
    colour: "Cognac",
    materials: ["Smooth cognac leather", "Hand-stitched edge"],
    features: ["Slip-in sleeve", "Stitched edge", "Fits most frames"],
    blurb: "A simple cognac sleeve for your glasses.",
    story: "One piece of cognac leather, folded and stitched along the edge. Slides into a pocket and takes the scratches so your lenses don't.",
    images: ["/img/acc/specs-sleeve-white.webp", "/img/acc/specs-sleeve-wood.webp"],
    swatch: "#7a3d1f",
  }),
  acc({
    slug: "folding-spectacle-case",
    name: "Folding Spectacle Case",
    line: "Snap-close glasses case",
    type: "Cases",
    colour: "Black pebble",
    materials: ["Pebble-grain leather", "Metal snap"],
    features: ["Folds flat", "Snap closure", "Structured sides"],
    blurb: "Pebble-grain case that folds flat when empty.",
    story: "A clever folding case in black pebble-grain leather — triangular sides fold in to form the case and flatten out when it's empty.",
    images: ["/img/acc/specs-case-white.webp", "/img/acc/specs-case-wood.webp", "/img/acc/specs-case-wood-2.webp"],
    swatch: "#202020",
  }),
  acc({
    slug: "hook-keychain",
    name: "Hook Keychain",
    line: "Embossed leather key clip",
    type: "Keychains",
    colour: "Black / Oxblood",
    materials: ["Snake- & croc-embossed leather", "Matte black hook", "Snap fastener"],
    features: ["Carabiner-style hook", "Snap loop", "Key ring"],
    blurb: "Embossed leather on a matte black hook.",
    story: "A strip of embossed leather snapped around a matte black hook — clips to a belt loop or bag strap.",
    images: ["/img/acc/hook-keychains-white.webp"],
    swatch: "#5a1f1a",
  }),
  acc({
    slug: "loop-keychain",
    name: "Loop Keychain",
    line: "Woven-texture leather loop",
    type: "Keychains",
    colour: "Tan / Brown",
    materials: ["Woven-texture leather", "Metal ring", "Rivet"],
    features: ["Folded leather loop", "Riveted", "Split ring"],
    blurb: "Folded woven-texture leather, riveted onto a ring.",
    story: "A folded loop of woven-texture leather, riveted and fitted with a split ring. Makes a good corporate gift — ask us about logos.",
    images: ["/img/acc/loop-keychains-dark.webp", "/img/acc/loop-keychains-dark-2.webp"],
    swatch: "#a8703f",
  }),
  acc({
    slug: "clip-keychain",
    name: "Clip Keychain",
    line: "Leather & metal key clip",
    type: "Keychains",
    colour: "Black",
    materials: ["Black leather", "Polished metal clip"],
    features: ["Spring clip", "Leather strap", "Key ring"],
    blurb: "Black leather strap with a polished spring clip.",
    story: "A short black leather strap between a polished spring clip and a key ring.",
    images: ["/img/acc/clip-keychains-dark.webp"],
    swatch: "#1b1b1b",
  }),
  acc({
    slug: "drop-keychain",
    name: "Drop Keychain",
    line: "Leaf-shaped leather fob",
    type: "Keychains",
    colour: "Assorted",
    materials: ["Assorted embossed leathers", "Snap", "Metal ring"],
    features: ["Leaf-shaped fob", "Snap fastener", "Many colours"],
    blurb: "Leaf-shaped fobs in whatever leather is on the bench.",
    story: "Cut from the offcuts of bigger pieces, so each batch comes in a mix of colours and textures. Nothing goes to waste.",
    images: ["/img/acc/drop-keychains-wood.webp"],
    swatch: "#2e8fb8",
  }),
  acc({
    slug: "travel-shoe-horn",
    name: "Travel Shoe Horn",
    line: "Leather-sleeved shoe horn",
    type: "Travel",
    colour: "Black",
    materials: ["Pebble-grain leather", "Polished steel", "Snap"],
    features: ["Folds into leather sleeve", "Hand-stitched edge", "Snap closure"],
    blurb: "A steel shoe horn that folds into a stitched sleeve.",
    story: "A polished steel shoe horn that swings out of a hand-stitched pebble-leather sleeve. Lives in a suitcase pocket.",
    images: ["/img/acc/shoe-horn-wood.webp", "/img/acc/shoe-horn-wood-2.webp"],
    swatch: "#232323",
  }),
  acc({
    slug: "desk-pen-stand",
    name: "Desk Pen Stand",
    line: "Leather pen rest",
    type: "Desk",
    colour: "Black",
    materials: ["Black leather", "Stitched edge"],
    features: ["Holds 3–4 pens", "Stitched leather", "Weighted base"],
    blurb: "A small black leather stand that keeps pens upright.",
    story: "A neat stitched-leather stand for the pens you actually use.",
    images: ["/img/acc/pen-stand-wood.webp"],
    swatch: "#1d1d1d",
  }),
  acc({
    slug: "card-stand",
    name: "Card Stand",
    line: "Desk card holder",
    type: "Desk",
    colour: "Black",
    materials: ["Black leather", "Contrast stitching"],
    features: ["Angled card rest", "Contrast stitch", "Flat base"],
    blurb: "A stitched leather stand for visiting cards.",
    story: "A desk stand for your visiting cards, edged with a contrast stitch. Ask about adding your company logo.",
    images: ["/img/acc/card-stand-wood.webp"],
    swatch: "#1e1e1e",
  }),
  acc({
    slug: "envelope-folio",
    name: "Envelope Folio",
    line: "Document envelope",
    type: "Desk",
    colour: "Tan / Navy / Blue",
    materials: ["Smooth leather", "Metal clasp"],
    features: ["Envelope flap", "Clasp closure", "A4 & smaller sizes"],
    blurb: "A leather envelope for documents, in three colours.",
    story: "A leather document envelope with a clasp — tan, navy or blue. Good for certificates, contracts, and gifting.",
    images: ["/img/acc/envelope-folios-wood.webp", "/img/acc/envelope-folios-wood-2.webp"],
    swatch: "#a46a3c",
  }),
  acc({
    slug: "wall-pocket",
    name: "Wall Pocket",
    line: "Switchboard organiser",
    type: "Home",
    colour: "Brown",
    materials: ["Brown leather", "Stitched pocket"],
    features: ["Hangs on a switchboard", "Holds remotes & phone", "Cut-out window"],
    blurb: "Hangs on the switchboard and holds the remotes.",
    story: "A clever little leather pocket that hangs over a switchboard plate and holds the AC remote and your phone. Very Indian, very useful.",
    images: ["/img/acc/wall-pocket-wood.webp", "/img/acc/wall-pocket-mounted.webp"],
    swatch: "#6e3f22",
  }),
];

export const categories: { key: Category; label: string; blurb: string }[] = [
  { key: "footwear", label: "Footwear", blurb: "Slides, thongs and toe-rings, built on padded footbeds." },
  { key: "bags", label: "Bags", blurb: "Briefcases, duffels and backpacks for a working life." },
  { key: "accessories", label: "Accessories", blurb: "Small leather goods for the desk, the pocket and the road." },
];

export const bySlug = (slug: string) => products.find((p) => p.slug === slug);

export function indexOf(p: Product) {
  return String(products.indexOf(p) + 1).padStart(2, "0");
}

export function related(p: Product, n = 4) {
  const same = products.filter((x) => x.category === p.category && x.slug !== p.slug);
  const other = products.filter((x) => x.category !== p.category);
  return [...same.slice(0, n), ...other].slice(0, n);
}

export const signature = products.filter((p) => p.signature);
